server:
  port: 8101
eureka:
  instance:
    hostname: 192.168.8.101
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/